spring.application.name=Visa-backOffice

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_visa
spring.datasource.username=postgres
spring.datasource.password=bolo1925

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

app.upload-dir=uploads/pieces-jointes